/**
 * Typed navigation helpers generated by next-intl.
 * Import Link, useRouter, usePathname, redirect from here
 * instead of from 'next/navigation' to get locale-aware routing.
 */
import { createNavigation } from 'next-intl/navigation'
import { routing }          from './i18n/routing'

export const { Link, redirect, usePathname, useRouter } = createNavigation(routing)
